### ISSUE TITLE
Error message after clicking on "download"

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_islandora_bagit#1]
Collection tested: https://dev-01.cwrc.ca/islandora/object/islandora%3A9fe199f8-b2d7-4cae-94ce-27ecf0210703

<img width="1282" alt="screen shot 2018-06-05 at 2 56 32 pm" src="https://user-images.githubusercontent.com/6600070/41004239-75639bda-68d6-11e8-890b-94ec0786a0dd.png">

The download went OK though.

**Comment by nikathone** [comment]
Now this should be fixed. the error won't show up unless the user try to submit an empty tree.
