### ISSUE TITLE
Improve "loading" animation

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_islandora_bagit#2]
@nikathone , 

Could you replace the "loading" animation you currently use and brand it with the CWRC colours (https://drive.google.com/drive/folders/0B4CtWuyM04e4dHk2QW9HNmt3aVE)

This one seems a bit smudgy:

![jun-05-2018 15-43-52](https://user-images.githubusercontent.com/6600070/41004499-5469108a-68d7-11e8-975f-61ca1e7b2d95.gif)

**Comment by nikathone** [comment]
@ilovan I changed the loader gif to the one with the secondary color #2A2A25. You can check it out at https://dev-01.cwrc.ca/islandora/object/islandora%3A6cfabe0e-ccc3-4907-a412-f52e96d2713c/manage/bagit

**Comment by ilovan** [comment]
Great, thanks, is there any way to get it to look less pixelated? (It seems a bit smudgy on my screen because of that)

**Comment by nikathone** [comment]
I switched to use SVG instead of GIF. What do you think?
