### ISSUE TITLE
Override actual file size for collection and IA book objects and replace with sum of the children/pages

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_islandora_bagit#3]
@nikathone , how difficult would it be to do this (I think things may get complicated when you have nested collections)

If this is too complicated or too time-consuming, we should consider removing the "size" from the collection and IA book nodes in the interface, since they are misleading. 

Any thoughts, @SusanBrown

**Comment by nikathone** [comment]
Right now the bag it module give the size of each object either it has descendants or not and that what is displayed beside the object checkbox label. Not sure if we need to clarify to the end user what those sizes mean...

**Comment by ilovan** [comment]
@nikathone , users would expect the size of the collection to reflect the sum of all the objects in the collection and the size of the book to reflect the sum of all the pages. 

This is how a local or cloud file system displays size. 

How difficult would it be implement this behaviour in your object tree?

**Comment by ilovan** [comment]
If too difficult, we prefer that you don't display the size on these two object types at all.

**Comment by nikathone** [comment]
@ilovan as discussed in slack this can be tested at https://dev-01.cwrc.ca/islandora/object/emic%3A20907/manage/bagit
